name: Experiment with paths-ignore

on:
  push:
    paths:
      - '**'
      - '!README.md'
  pull_request:
    types: [open]
    paths:
      - '**'
      - '!README.md'
jobs:
  echo-date:
    runs-on: ubuntu-latest
    name: "Echo"
    
    steps:
      - name: Run echo date
        run: |
          echo -e "Hello at $(date -I)"
