name: Experiment with paths-ignore

on:
  push:
    paths-ignore:
      - 'README.md'
      - '**'
  pull_request:
    types: [open]
    paths-ignore:
      - 'README.md'
      - '**'
jobs:
  echo-date:
    runs-on: ubuntu-latest
    name: "Echo"
    
    steps:
      - name: Run echo date
        run: |
          echo -e "Hello at $(date -I)"
